export const TECHNICAL_GLOSSARY: Record<string, string> = {
  "dashboard": "A visual interface showing project progress, metrics, and data.",
  "server": "A computer or system that provides resources or services to other computers.",
  "bug": "An error or problem in software that prevents it from working correctly.",
  "workflow": "A sequence of tasks or processes to complete a project.",
  "developer": "A professional who writes and maintains software.",
  "ppe": "Personal Protective Equipment (gear to protect the wearer).",
  "boots": "Protective footwear to protect feet from chemicals or injuries.",
  "helmet": "Hard hat to protect the head from falling objects.",
  "goggles": "Protective eyewear to shield eyes from splashes or debris.",
  "hazard": "A potential source of harm or danger.",
  "forklift": "A vehicle used to lift and move materials in a warehouse.",
  "algorithm": "A set of rules to be followed in calculations or problem-solving.",
  "automation": "The use of technology to reduce human intervention in processes.",
  "cloud computing": "Storing and accessing data over the internet instead of a hard drive.",
  "data mining": "Extracting useful information from large sets of data.",
  "supply chain": "The network involved in producing and delivering a product.",
  "logistics": "The detailed coordination of complex operations involving people, facilities, or supplies.",
  "actuator": "A component that moves or controls a mechanism.",
  "arm": "A mechanical part resembling a human arm, used in robotics.",
  "assembly": "The process of putting together parts to make a machine.",
  "sensor": "A device that detects or measures a physical property.",
  "circuit": "A complete path around which an electric current flows.",
  "compliance": "The action of complying with a command or rule.",
  "drill": "A tool or machine with a rotating cutting tip.",
  "incident": "An event that is either unpleasant or unusual.",
  "maintenance": "The process of preserving a condition or situation.",
  "firewall": "A system designed to block unauthorized access to a network.",
  "audit": "An official inspection of accounts or safety procedures.",
  "database": "A structured set of data held in a computer.",
  "backend": "The server-side part of an application.",
  "frontend": "The user interface of an application.",
  "api": "Interface allowing different applications to communicate.",
  "array": "A data structure consisting of a collection of elements.",
  "boolean": "A data type with two possible values: true or false.",
  "cache": "Hardware or software that stores data for faster retrieval.",
  "compiler": "A program that translates code into machine language.",
  "debug": "To identify and remove errors from software.",
  "framework": "A platform for developing software applications.",
  "git": "A version control system for tracking changes in code.",
  "loop": "A programming structure that repeats a sequence of instructions.",
  "parameter": "A value passed to a function.",
  "repository": "A central location where data or code is stored.",
  "runtime": "The time during which a program is running.",
  "script": "A list of commands executed by a program.",
  "syntax": "The set of rules that defines the combinations of symbols in code.",
  "variable": "A storage location paired with an associated symbolic name.",
  "encryption": "Encoding data to prevent unauthorized access.",
  "biometrics": "Measurement of physical characteristics for identification.",
  "blockchain": "A decentralized digital ledger of transactions.",
  "chatbot": "Software that simulates conversation with human users.",
  "clustering": "Grouping a set of objects in such a way that objects in the same group are more similar.",
  "forecasting": "Predicting future trends based on data.",
  "hyperparameter": "A configuration variable used to tune a machine learning model.",
  "overfitting": "When a model matches training data too closely, failing to generalize.",
  "tokenization": "Breaking text into smaller units (tokens).",
  "tuning": "Adjusting model parameters to improve performance.",
  "accessibility": "Designing products to be usable by people with disabilities.",
  "agile": "A project management method involving iterative development.",
  "deployment": "Making a software system available for use.",
  "integration": "Combining different computing systems or software.",
  "localization": "Adapting a product to a specific locale or market.",
  "mockup": "A visual model of a design or product.",
  "onboarding": "The process of integrating a new employee or user.",
  "roadmap": "A strategic plan defining a goal or desired outcome.",
  "scaffold": "A temporary structure for support.",
  "timeline": "A schedule of events or tasks.",
  "cargo": "Goods carried on a ship, aircraft, or vehicle.",
  "freight": "Goods transported in bulk.",
  "inventory": "A complete list of items in stock.",
  "shipment": "The action of shipping goods.",
  "warehouse": "A large building for storing goods.",
  "invoice": "A bill for goods or services.",
  "receipt": "Proof of payment or delivery.",
  "tracking": "Monitoring the movement or progress of something."
};